import glob

# OUTPUT PATH FOR THE FINAL COMBINED MATRIX
FINAL_MATRIX_OP = ""

# BASE PATH WHERE YOU HAVE YOUR GRAPHS
GRAPHS_BP = "/Users/arjuns/Downloads/fyp/scraping/new/graphs"

# GLOB CODE TO PULL ALL GRAPHS
LIST_OF_FILES = glob.glob(f'{GRAPHS_BP}/*/*.graphml')

# TOTAL NUMBER OF GRAPHS
TOTAL_GRAPHS = 204

# ANY GRAPHS WITH NO NODES, IF ANY
FILES_WITH_NO_NODES = []

# SIZES OF EACH SUBSET. THIS WILL BE PRINTED IN COMMAND LINE WHEN combination_kmatrix.py is run.
SIZES = [21,21,21,21,20,20,20,20,20,20]
